import type { Metadata } from 'next'
import { Inter, Poppins, Roboto_Condensed, EB_Garamond } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/providers/theme-provider'
import { Nav } from '@/components/navigation/nav'
import { cn } from '@/lib/utils'
import BackButton from '@/components/ui/back-button'

export const metadata: Metadata = {
  title: 'Manjus Classroom',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['600'],
  variable: '--font-poppins',
})

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-inter',
})

const roboto_condensed = Roboto_Condensed({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-roboto-condensed',
})

const dm_serif_display = EB_Garamond({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-dm-serif-display',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <html
        className="!scroll-smooth"
        lang="en"
        suppressHydrationWarning={true}
      >
        <head />
        <body
          className={cn(
            `${poppins.variable} ${inter.variable} ${roboto_condensed.variable} ${dm_serif_display.variable} flex flex-col min-h-screen bg-background antialiased`
          )}
        >
          <Nav />
          <BackButton />
          {children}
        </body>
      </html>
    </>
  )
}
